services:
  numbas_container:
    build: .
    container_name: numbas_editor
    ports:
      - "8000:8000"
      - "8080:80"
      - "9000:9000"
    environment:
      - EDITOR_PASSWORD=${EDITOR_PASSWORD}