services:
  numbas_container:
    build: .
    container_name: numbas_editor
    ports:
      - "8000:8000"
      - "8080:80"
    environment:
      - EDITOR_PASSWORD=${EDITOR_PASSWORD}
    volumes:
      - numbas_data:/srv/numbas
      - mysql_data:/var/lib/mysql

volumes:
  numbas_data:
  mysql_data: